// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Create a new library folder at `path`, open it, and make it current. */
	createLibrary: (path: string) => typedError<LibraryInfo, AppError>(__TAURI_INVOKE("create_library", { path })),
	/**
	 *  Open an existing library at `path` (migrating forward if needed) and make
	 *  it current.
	 */
	openLibrary: (path: string) => typedError<LibraryInfo, AppError>(__TAURI_INVOKE("open_library", { path })),
	/**
	 *  Close the current library (welcome screen / library switcher). No-op when
	 *  nothing is open.
	 */
	closeLibrary: () => typedError<null, AppError>(__TAURI_INVOKE("close_library")),
	/**
	 *  Reopen the library from the previous session, if it is still there.
	 *  Called by the route guard on startup — failures degrade to the welcome
	 *  screen (and clear the stale pointer), never a blocked launch.
	 */
	reopenLastLibrary: () => typedError<{
	path: string,
	name: string,
	library_id: string,
	/**  Unix ms. */
	created_at: number | null,
} | null, AppError>(__TAURI_INVOKE("reopen_last_library")),
	/**
	 *  The library the app currently has open, if any — the router guard's
	 *  source of truth.
	 */
	getCurrentLibrary: () => typedError<{
	path: string,
	name: string,
	library_id: string,
	/**  Unix ms. */
	created_at: number | null,
} | null, AppError>(__TAURI_INVOKE("get_current_library")),
	/**
	 *  Recently opened libraries, most recent first, with a `missing` flag for
	 *  folders that have moved or been deleted.
	 */
	listRecentLibraries: () => typedError<RecentLibrary[], AppError>(__TAURI_INVOKE("list_recent_libraries")),
	/**  Remove one entry from the recent list (does not touch the folder). */
	removeRecentLibrary: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_recent_library", { path })),
	/**
	 *  One aggregate query over `assets` — cheap enough to refetch after any
	 *  mutation that could move the counters.
	 */
	getLibraryStats: () => typedError<LibraryStats, AppError>(__TAURI_INVOKE("get_library_stats")),
	/**
	 *  Start importing `paths` (files and/or directories, absolute) into the
	 *  current library, optionally attaching every imported asset to `folder_id`.
	 * 
	 *  `keep_duplicates` disables the library-wide exact-dedupe (the Duplicate
	 *  Alert's "keep both" path); batch-internal repeats are still collapsed.
	 */
	importPaths: (paths: string[], folderId: string | null, keepDuplicates: boolean) => typedError<ImportStarted, AppError>(__TAURI_INVOKE("import_paths", { paths, folderId, keepDuplicates })),
	/**
	 *  Signal cancellation for an in-flight import. Already-committed files stay;
	 *  the job still emits its terminal `ImportFinished { cancelled: true }`.
	 */
	cancelImport: (jobId: string) => typedError<null, AppError>(__TAURI_INVOKE("cancel_import", { jobId })),
	/**
	 *  Import whatever the clipboard holds (⌘V): copied files take priority,
	 *  then a raw bitmap (screenshots, browser "Copy Image") which is written to
	 *  a temp PNG and fed through the regular pipeline — so hashing/dedupe/
	 *  thumbnails/events all behave exactly like a file import.
	 * 
	 *  Returns `Conflict` when the clipboard has nothing importable (the frontend
	 *  shows a quiet info toast for that code).
	 */
	importClipboard: (folderId: string | null) => typedError<ImportStarted, AppError>(__TAURI_INVOKE("import_clipboard", { folderId })),
	listAssets: (query: AssetListQuery) => typedError<AssetListResult, AppError>(__TAURI_INVOKE("list_assets", { query })),
	/**
	 *  Every asset id matching this query's scope+search+facets, in sort order and
	 *  unpaged — backs "select all" so it covers rows not yet loaded by the grid.
	 */
	listAssetIds: (query: AssetListQuery) => typedError<string[], AppError>(__TAURI_INVOKE("list_asset_ids", { query })),
	getAsset: (id: string) => typedError<AssetDetail, AppError>(__TAURI_INVOKE("get_asset", { id })),
	updateAsset: (id: string, patch: AssetPatch) => typedError<AssetDetail, AppError>(__TAURI_INVOKE("update_asset", { id, patch })),
	/**  Set the same rating on many assets at once (batch metadata editing). */
	setAssetsRating: (assetIds: string[], rating: number) => typedError<number, AppError>(__TAURI_INVOKE("set_assets_rating", { assetIds, rating })),
	/**
	 *  Reveal the managed file in Finder / Explorer. The frontend never learns
	 *  the absolute path — the OS shows it directly.
	 */
	revealAsset: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_asset", { id })),
	/**
	 *  Assets still missing a cover whose format the WebView (not headless Rust)
	 *  must decode: video, PDF, and HEIC/HEIF. The worker grabs a frame/page/image
	 *  with the engine's own decoder and ships it back (see `set_video_thumbnail`
	 *  for video, `set_captured_thumbnail` for the rest). Extension list mirrors
	 *  `VIDEO_EXTS` and the HEIC/PDF handling in `src/lib/viewer-registry.ts`.
	 */
	listCoverCandidates: () => typedError<CoverCandidate[], AppError>(__TAURI_INVOKE("list_cover_candidates")),
	/**
	 *  Store a frontend-captured video frame as the asset's cover and record
	 *  playback metadata. `video_*`/`duration_ms` describe the SOURCE video, not
	 *  the captured frame.
	 */
	setVideoThumbnail: (assetId: string, frameBase64: string, videoWidth: number, videoHeight: number, durationMs: number | null) => typedError<null, AppError>(__TAURI_INVOKE("set_video_thumbnail", { assetId, frameBase64, videoWidth, videoHeight, durationMs })),
	/**
	 *  Store a frontend-captured cover for a non-video format the WebView decoded
	 *  (PDF page 1, HEIC image). `width`/`height` are the SOURCE page/image size.
	 *  No duration is recorded — that column is video-only.
	 */
	setCapturedThumbnail: (assetId: string, frameBase64: string, width: number, height: number) => typedError<null, AppError>(__TAURI_INVOKE("set_captured_thumbnail", { assetId, frameBase64, width, height })),
	/**
	 *  Regenerate thumbnails for alive `managed` assets that lack one but whose
	 *  format is decodable headless in Rust (TIFF/ICO/PSD/Sketch added after they
	 *  were first imported). Best-effort: per-asset failures are logged and skipped;
	 *  formats needing the WebView (video/PDF/HEIC) are left to the capture worker.
	 *  Returns the number of covers filled — a cheap no-op when nothing is pending.
	 */
	backfillMissingThumbnails: () => typedError<number, AppError>(__TAURI_INVOKE("backfill_missing_thumbnails")),
	/**
	 *  Visual similarity search (dHash, layer L2 of the duplicate strategy):
	 *  popcount the target's fingerprint against every alive asset, return
	 *  summaries ordered by distance (the target itself leads at distance 0).
	 *  Capped at 200 hits — also keeps the follow-up IN() under SQLite's
	 *  parameter limit.
	 */
	findSimilarAssets: (assetId: string, maxDistance: number) => typedError<AssetSummary[], AppError>(__TAURI_INVOKE("find_similar_assets", { assetId, maxDistance })),
	/**  Scan the whole library for exact and visual duplicates. */
	scanDuplicates: () => typedError<DuplicateScan, AppError>(__TAURI_INVOKE("scan_duplicates")),
	listSmartFolders: () => typedError<SmartFolder[], AppError>(__TAURI_INVOKE("list_smart_folders")),
	createSmartFolder: (name: string, rules: SmartRules) => typedError<SmartFolder, AppError>(__TAURI_INVOKE("create_smart_folder", { name, rules })),
	updateSmartFolder: (id: string, name: string | null, rules: {
	/**  `false` = every condition must hold (AND); `true` = any may (OR). */
	match_any: boolean,
	conditions: SmartCondition[],
} | null) => typedError<null, AppError>(__TAURI_INVOKE("update_smart_folder", { id, name, rules })),
	deleteSmartFolder: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_smart_folder", { id })),
	/**  Flat folder list, siblings ordered by manual position then name. */
	listFolders: () => typedError<Folder[], AppError>(__TAURI_INVOKE("list_folders")),
	/**  Direct-member aggregate (count + total bytes) for the folder info panel. */
	getFolderStats: (folderId: string) => typedError<FolderStats, AppError>(__TAURI_INVOKE("get_folder_stats", { folderId })),
	/**
	 *  Folder ids that contain ALL of the given assets (intersection) — drives the
	 *  folder picker's checked state across a single- or multi-asset selection.
	 */
	foldersForAssets: (assetIds: string[]) => typedError<string[], AppError>(__TAURI_INVOKE("folders_for_assets", { assetIds })),
	createFolder: (name: string, parentId: string | null) => typedError<Folder, AppError>(__TAURI_INVOKE("create_folder", { name, parentId })),
	renameFolder: (id: string, name: string) => typedError<Folder, AppError>(__TAURI_INVOKE("rename_folder", { id, name })),
	/**  Set (or clear, via empty string) a folder's description. */
	setFolderDescription: (id: string, description: string) => typedError<Folder, AppError>(__TAURI_INVOKE("set_folder_description", { id, description })),
	moveFolder: (id: string, newParentId: string | null, position: number) => typedError<null, AppError>(__TAURI_INVOKE("move_folder", { id, newParentId, position })),
	/**
	 *  Delete a folder and its whole subtree. Assets are never deleted — their
	 *  membership rows cascade away and they fall back to "uncategorized"
	 *  (Eagle semantics).
	 */
	deleteFolder: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_folder", { id })),
	addAssetsToFolder: (assetIds: string[], folderId: string) => typedError<number, AppError>(__TAURI_INVOKE("add_assets_to_folder", { assetIds, folderId })),
	removeAssetsFromFolder: (assetIds: string[], folderId: string) => typedError<number, AppError>(__TAURI_INVOKE("remove_assets_from_folder", { assetIds, folderId })),
	trashAssets: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("trash_assets", { ids })),
	restoreAssets: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("restore_assets", { ids })),
	/**
	 *  Permanently delete specific trashed assets (rows first, then files).
	 *  Ids that are not in the trash are ignored.
	 */
	deleteAssetsForever: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_assets_forever", { ids })),
	/**  Permanently delete everything in the trash. */
	emptyTrash: () => typedError<number, AppError>(__TAURI_INVOKE("empty_trash")),
	/**  All tags with usage counts, name-ordered. */
	listTags: () => typedError<Tag[], AppError>(__TAURI_INVOKE("list_tags")),
	/**
	 *  Create-or-get by (case-insensitive) name. An existing tag is returned
	 *  as-is; `color` only applies when the tag is newly created.
	 */
	createTag: (name: string, color: string | null) => typedError<Tag, AppError>(__TAURI_INVOKE("create_tag", { name, color })),
	/**
	 *  Rename and/or recolor. Renaming onto another existing tag is rejected
	 *  (merge semantics are a later feature, not an accident).
	 */
	updateTag: (id: string, name: string | null, color: string | null) => typedError<Tag, AppError>(__TAURI_INVOKE("update_tag", { id, name, color })),
	/**  Delete a tag; memberships cascade away, assets are untouched. */
	deleteTag: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_tag", { id })),
	/**  Attach every tag to every asset (cartesian, INSERT OR IGNORE). */
	addTagsToAssets: (assetIds: string[], tagIds: string[]) => typedError<number, AppError>(__TAURI_INVOKE("add_tags_to_assets", { assetIds, tagIds })),
	removeTagsFromAssets: (assetIds: string[], tagIds: string[]) => typedError<number, AppError>(__TAURI_INVOKE("remove_tags_from_assets", { assetIds, tagIds })),
	listWatchedFolders: () => typedError<WatchedFolder[], AppError>(__TAURI_INVOKE("list_watched_folders")),
	addWatchedFolder: (path: string, folderId: string | null) => typedError<WatchedFolder, AppError>(__TAURI_INVOKE("add_watched_folder", { path, folderId })),
	setWatchedFolderEnabled: (id: string, enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_watched_folder_enabled", { id, enabled })),
	removeWatchedFolder: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_watched_folder", { id })),
	getMaintenanceReport: () => typedError<MaintenanceReport, AppError>(__TAURI_INVOKE("get_maintenance_report")),
	/**  Reclaim free database pages. Returns bytes reclaimed. */
	vacuumDatabase: () => typedError<number | null, AppError>(__TAURI_INVOKE("vacuum_database")),
	/**  `PRAGMA integrity_check` — true when the database is healthy. */
	verifyIntegrity: () => typedError<boolean, AppError>(__TAURI_INVOKE("verify_integrity")),
	/**
	 *  Delete orphan asset/thumbnail files (irreversible — no soft delete). Refused
	 *  while an import is in flight, since a mid-import file has no DB row yet and
	 *  would be misread as orphaned.
	 */
	cleanOrphans: () => typedError<OrphanCleanup, AppError>(__TAURI_INVOKE("clean_orphans")),
	/**  Copy `ids` into `dest_dir`. Returns the number of files written. */
	exportAssets: (ids: string[], destDir: string) => typedError<number, AppError>(__TAURI_INVOKE("export_assets", { ids, destDir })),
	searchSource: (provider: SourceProvider, query: string, page: number, filters: SourceFilters, apiKey: string | null) => typedError<SourceSearchResult, AppError>(__TAURI_INVOKE("search_source", { provider, query, page, filters, apiKey })),
	importSourceItems: (items: SourceItem[], folderId: string | null) => typedError<ImportSummary, AppError>(__TAURI_INVOKE("import_source_items", { items, folderId })),
	/**
	 *  If the clipboard holds *only* a web URL (no copied files or bitmap, which
	 *  `import_clipboard` handles and which take priority), return it normalized.
	 *  `⌘V` calls this before `import_clipboard`; `None` means "not a URL paste".
	 */
	clipboardUrl: () => typedError<string | null, AppError>(__TAURI_INVOKE("clipboard_url")),
	importUrl: (url: string, folderId: string | null) => typedError<UrlImport, AppError>(__TAURI_INVOKE("import_url", { url, folderId })),
	/**
	 *  Open a link asset's page in the in-app browser window (reused across links).
	 *  Renders the live site — it's a top-level webview load, not an iframe.
	 */
	openLinkWindow: (url: string, title: string | null) => typedError<null, AppError>(__TAURI_INVOKE("open_link_window", { url, title })),
	getCollectStatus: () => typedError<CollectStatus, AppError>(__TAURI_INVOKE("get_collect_status")),
	setCollectEnabled: (enabled: boolean) => typedError<CollectStatus, AppError>(__TAURI_INVOKE("set_collect_enabled", { enabled })),
	regenerateCollectToken: () => typedError<CollectStatus, AppError>(__TAURI_INVOKE("regenerate_collect_token")),
};

/** Events */
export const events = {
	collectImported: makeEvent<CollectImported>("collect-imported"),
	importFinished: makeEvent<ImportFinished>("import-finished"),
	importProgress: makeEvent<ImportProgress>("import-progress"),
};

/* Types */
export type AppError = { code: "NotFound"; detail: string } | { code: "Io"; detail: string } | { code: "Db"; detail: string } | 
/**  A command that requires an open library was called without one. */
{ code: "NoLibraryOpen" } | 
/**
 *  The folder is not a yAssets library, is damaged, or was written by a
 *  newer app version (schema ahead of this build's migrations).
 */
{ code: "LibraryIncompatible"; detail: string } | 
/**
 *  The operation conflicts with current state (target not empty, folder
 *  cycle, import in flight while switching libraries, …).
 */
{ code: "Conflict"; detail: string } | 
/**  A third-party source request failed (offline, timeout, bad response). */
{ code: "Network"; detail: string } | 
/**
 *  A third-party source answered 429 — the caller should wait and retry.
 *  Split from `Network` so the UI can say "slow down" instead of
 *  "check your connection".
 */
{ code: "RateLimited"; detail: string } | 
/**  User-visible catch-all. Internal details belong in the logs, not here. */
{ code: "Internal" };

/**  Inspector payload — summary plus the heavier/editable fields. */
export type AssetDetail = {
	id: string,
	name: string,
	ext: string,
	mime: string | null,
	size: number | null,
	width: number | null,
	height: number | null,
	has_thumb: boolean,
	rating: number,
	/**  `"file"` or `"link"` — see `AssetSummary::kind`. */
	kind: string,
	note: string,
	hash_blake3: string,
	/**  Original path at import time (provenance display only). */
	src_path: string | null,
	/**  User-editable source link (e.g. where the asset came from). */
	url: string | null,
	folder_ids: string[],
	tags: TagRef[],
	/**  Representative swatch hexes (JSON-decoded from the DB), for display. */
	palette: string[],
	imported_at: number | null,
	file_mtime: number | null,
	file_ctime: number | null,
	updated_at: number | null,
	deleted_at: number | null,
};

export type AssetListQuery = {
	scope: AssetScope,
	/**  Full-text query over name + note (FTS5). None/empty = no text filter. */
	search: string | null,
	/**
	 *  Ad-hoc facets applied ON TOP of `scope` (orthogonal to it).
	 *  Minimum star rating (inclusive).
	 */
	rating_min: number | null,
	/**  Keep only these lowercase extensions (ANY-of). */
	types: string[] | null,
	/**  Keep assets carrying ANY of these tag ids. */
	tag_ids: string[] | null,
	sort: SortKey,
	dir: SortDir,
	/**
	 *  Keyset pagination: fetch the page strictly after this boundary. When set,
	 *  `offset` is ignored (cursor replaces it). Absent = first page.
	 */
	cursor: ListCursor | null,
	/**  Legacy offset paging (still honored when `cursor` is None). */
	offset: number | null,
	limit: number | null,
};

export type AssetListResult = {
	items: AssetSummary[],
	/**  Total rows matching scope+search, ignoring offset/limit. */
	total: number,
};

/**  Partial update — absent fields stay untouched. */
export type AssetPatch = {
	name: string | null,
	note: string | null,
	rating: number | null,
	/**  `Some("")` clears the link. */
	url: string | null,
};

/**
 *  Which slice of the catalog a list query targets. Exported to TS as a
 *  discriminated union on `kind`.
 */
export type AssetScope = { kind: "all" } | { kind: "uncategorized" } | { kind: "untagged" } | { kind: "recent"; days: number } | { kind: "folder"; folder_id: string } | { kind: "tag"; tag_id: string } | { kind: "color"; hue: number } | 
/**  Saved rule set (see `commands::smart_folders`) resolved at list time. */
{ kind: "smart_folder"; smart_folder_id: string } | { kind: "trash" };

/**  Everything the grid card needs — ~200 bytes/row over IPC. */
export type AssetSummary = {
	id: string,
	name: string,
	ext: string,
	/**  Bytes. */
	size: number | null,
	/**  Post-EXIF-orientation pixel dimensions; None for non-decoded formats. */
	width: number | null,
	height: number | null,
	has_thumb: boolean,
	rating: number,
	/**
	 *  `"file"` (normal managed file) or `"link"` (a bookmark whose cover is the
	 *  page's Open Graph image). Drives the grid's link badge + open-in-browser.
	 */
	kind: string,
	/**
	 *  Source/provenance URL. Carried on the summary so a link card can show its
	 *  host and open in the browser without an extra fetch. None for most files.
	 */
	url: string | null,
	/**  Unix ms. */
	imported_at: number | null,
	/**
	 *  Unix ms of last metadata edit — carried so the keyset cursor for the
	 *  UpdatedAt sort can be built from the loaded row.
	 */
	updated_at: number | null,
	/**  Source video duration in ms; None for non-video / not-yet-probed. */
	duration_ms: number | null,
};

/**
 *  A capture arrived through the Collect API (yClip browser extension).
 *  The frontend toasts it and refreshes the asset lists — server-side imports
 *  bypass the usual frontend mutation, so nothing else would invalidate them.
 */
export type CollectImported = {
	/**  `"link"` (a bookmark) or `"media"` (a downloaded/uploaded file). */
	kind: string,
	title: string,
	/**  Already in the library — nothing new to show. */
	duplicate: boolean,
};

export type CollectStatus = {
	/**  The persisted preference (survives restarts). */
	enabled: boolean,
	/**  Whether a listener is actually bound right now. */
	running: boolean,
	/**  The bound port (41420-41424), when running. */
	port: number | null,
	/**  Bearer token for the extension; empty until first enabled. */
	token: string,
};

/**
 *  An asset the frontend capture worker should cover, plus its ext so the
 *  worker can pick the right decoder (video frame / PDF page / HEIC image).
 */
export type CoverCandidate = {
	id: string,
	ext: string,
};

/**
 *  An incoming file whose exact content (blake3) already exists in the
 *  library. Powers the interactive Duplicate Alert: "keep both" re-imports
 *  `src_path` with dedupe disabled; the existing asset's thumbnail stands in
 *  for both sides (identical bytes = identical pixels).
 */
export type DuplicateItem = {
	/**  Absolute source path of the incoming file. */
	src_path: string,
	/**  Incoming display name (file stem). */
	name: string,
	/**  Incoming file size in bytes. */
	size: number | null,
	/**  Id of the already-cataloged asset with identical content. */
	existing_id: string,
};

export type DuplicateScan = {
	/**  Groups of byte-identical assets (each group ≥ 2, ordered oldest-first). */
	exact: AssetSummary[][],
	/**  Clusters of visually-similar assets (across different hashes). */
	visual: AssetSummary[][],
};

export type Folder = {
	id: string,
	parent_id: string | null,
	name: string,
	position: number,
	/**  Alive (non-trashed) assets directly in this folder. */
	asset_count: number,
	/**  Unix ms. */
	created_at: number | null,
	/**  User notes shown in the folder info panel; None/empty = unset. */
	description: string | null,
};

/**
 *  Aggregate for the folder info panel — direct members only (matches the
 *  folder grid view and `asset_count`).
 */
export type FolderStats = {
	item_count: number,
	/**  Total bytes of the direct alive members. */
	total_size: number | null,
};

/**  One file that could not be imported, with a user-displayable reason. */
export type ImportFailure = {
	/**  Source path as given by the user (absolute). */
	path: string,
	reason: string,
};

/**  Terminal event for an import job — exactly one per `job_id`, even on cancel. */
export type ImportFinished = {
	job_id: string,
	/**  Newly inserted assets. */
	imported: number,
	/**  Duplicates (same blake3 hash) that were skipped. */
	skipped: number,
	failed: ImportFailure[],
	/**
	 *  Library-wide exact duplicates skipped this run (empty when the job ran
	 *  with dedupe disabled). Batch-internal repeats are not listed.
	 */
	duplicates: DuplicateItem[],
	/**  True when the job was cancelled before completing. */
	cancelled: boolean,
};

/**  Which stage of the import pipeline a progress event refers to. */
export type ImportPhase = 
/**
 *  Walking the dropped paths, expanding directories into a file list.
 *  `total` grows while discovering.
 */
"Discovering" | 
/**  Hashing / copying / thumbnailing / inserting files. `total` is final. */
"Processing";

/**  Throttled progress snapshot for an in-flight import job. */
export type ImportProgress = {
	job_id: string,
	phase: ImportPhase,
	/**  Files fully processed so far (imported + skipped + failed). */
	done: number,
	/**  Total files discovered for this job (grows during `Discovering`). */
	total: number,
	/**  Display name of the file currently being processed, if any. */
	current: string | null,
	/**  Files that failed so far. */
	failed: number,
};

export type ImportStarted = {
	job_id: string,
};

/**  Outcome tally for a batch "Add to Library". */
export type ImportSummary = {
	imported: number,
	/**  Batch-local repeats (the same item twice in one add). */
	skipped: number,
	/**  Already in the library (exact content) — the existing asset is kept. */
	duplicates: number,
	failed: number,
};

/**  Library descriptor crossing the IPC boundary. */
export type LibraryInfo = {
	path: string,
	name: string,
	library_id: string,
	/**  Unix ms. */
	created_at: number | null,
};

/**  Counters for the sidebar badges and the folder-summary panel. */
export type LibraryStats = {
	/**  Alive (non-trashed) assets. */
	total: number,
	/**  Alive assets that belong to no folder. */
	uncategorized: number,
	/**  Alive assets carrying no tag. */
	untagged: number,
	/**  Trashed assets. */
	trash: number,
	/**  Total size of alive assets, in bytes. */
	total_size: number | null,
};

/**
 *  Keyset page boundary: the previous page's last row. `sort_value` is that
 *  row's ACTIVE-sort-column value stringified (name verbatim; numeric sorts —
 *  imported_at/size/rating/updated_at — as a decimal integer string), `id` is
 *  its id. The next page is everything ordered strictly after (value, id).
 */
export type ListCursor = {
	sort_value: string,
	id: string,
};

/**  What the Maintenance pane displays before the user acts. */
export type MaintenanceReport = {
	/**  Database file size (excluding WAL), bytes. */
	db_bytes: number | null,
	/**  Files under assets/ with no live DB row. */
	orphan_asset_files: number,
	/**  Thumbnails under thumbs/ with no live DB row. */
	orphan_thumbnails: number,
};

export type OrphanCleanup = {
	asset_files: number,
	thumbnails: number,
};

/**
 *  IPC shape — `missing` is computed at list time so the welcome screen can
 *  grey out libraries whose folder has moved or been deleted.
 */
export type RecentLibrary = {
	path: string,
	name: string,
	/**  Unix ms. */
	last_opened_at: number | null,
	missing: boolean,
};

/**  One rule row. Exported to TS as a discriminated union on `field`. */
export type SmartCondition = 
/**  Extension is one of `values` (compared lowercased). */
{ field: "ext"; values: string[] } | 
/**  Filename contains `value` (case-insensitive via NOCASE-ish LIKE). */
{ field: "name_contains"; value: string } | { field: "rating_at_least"; min: number } | 
/**  Dominant-hue bucket equals `value` (0-11 chromatic, 12 neutral). */
{ field: "hue"; value: number } | { field: "has_tag"; tag_id: string } | { field: "added_within_days"; days: number };

export type SmartFolder = {
	id: string,
	name: string,
	rules: SmartRules,
	position: number,
};

export type SmartRules = {
	/**  `false` = every condition must hold (AND); `true` = any may (OR). */
	match_any: boolean,
	conditions: SmartCondition[],
};

export type SortDir = "Asc" | "Desc";

export type SortKey = "ImportedAt" | "Name" | "Size" | "Rating" | "UpdatedAt";

/**
 *  Provider-agnostic search filters. A flat bag of optionals: each provider
 *  reads only the fields it understands and ignores the rest, so the frontend
 *  can keep one filter state per provider without a type per source.
 */
export type SourceFilters = {
	/**  Wallhaven category bitmask "general/anime/people", e.g. "111". */
	categories: string | null,
	/**
	 *  Wallhaven purity bitmask "sfw/sketchy/nsfw", e.g. "100". Enforced to SFW
	 *  server-side when no API key is present.
	 */
	purity: string | null,
	/**  e.g. "date_added" | "relevance" | "views" | "toplist". */
	sorting: string | null,
	/**  "desc" | "asc". */
	order: string | null,
	/**  Wallhaven minimum resolution, e.g. "1920x1080". */
	atleast: string | null,
	/**  Wallhaven aspect ratios, e.g. "landscape" | "portrait" | "1x1". */
	ratios: string | null,
	/**  Pixabay image type: "photo" | "illustration" | "vector". */
	image_type: string | null,
	/**  Pixabay "horizontal" | "vertical"; Pexels "landscape" | "portrait" | "square". */
	orientation: string | null,
	/**  Pexels minimum size: "large" | "medium" | "small". */
	size: string | null,
	/**  Openverse license bucket: "commercial" | "modification". */
	license_type: string | null,
	/**  Openverse category: "photograph" | "illustration" | "digitized_artwork". */
	category: string | null,
	/**  Openverse aspect ratio: "wide" | "tall" | "square". */
	aspect_ratio: string | null,
	/**  Iconify icon-set prefix, e.g. "mdi". */
	prefix: string | null,
	/**  Iconify: true = color icon sets only, false = monochrome only. */
	palette: boolean | null,
	/**  Openverse media kind: "audio" routes to /v1/audio/; unset = images. */
	media_type: string | null,
};

/**  One browsable result from a provider. */
export type SourceItem = {
	provider: SourceProvider,
	/**  Provider-native id (grid key + dedupe). */
	id: string,
	/**  Remote thumbnail URL, shown directly in an `<img>` (CSP-allowlisted host). */
	thumb_url: string,
	/**  Full-resolution URL — downloaded by Rust on import, never by the webview. */
	full_url: string,
	/**  The provider page for this item; stored as the imported asset's `source`. */
	source_page_url: string,
	width: number,
	height: number,
	/**  File extension of the full-res asset (e.g. "jpg", "png"). */
	ext: string,
	/**  Attribution, when the provider supplies it (Pexels/Openverse). */
	author: string | null,
	license: string | null,
	/**
	 *  A ready-made, human-readable attribution line, when the provider gives
	 *  one (Openverse). Recorded on the imported asset's note for licenses that
	 *  require credit. Providers without one leave it `None` and the importer
	 *  falls back to `author` + `license`.
	 */
	attribution: string | null,
	/**  Track length for audio results (Openverse audio), in milliseconds. */
	duration_ms: number | null,
};

export type SourceProvider = "wallhaven" | "pixabay" | "openverse" | "pexels" | "iconify";

/**  A page of search results. */
export type SourceSearchResult = {
	items: SourceItem[],
	page: number,
	last_page: number,
};

export type Tag = {
	id: string,
	name: string,
	/**  Optional display color (hex like `#3b82f6`); None → neutral dot. */
	color: string | null,
	/**  Alive (non-trashed) assets carrying this tag. */
	asset_count: number,
	/**  Unix ms. */
	created_at: number | null,
};

/**  A tag as carried on an asset detail (no usage count needed here). */
export type TagRef = {
	id: string,
	name: string,
	color: string | null,
};

/**  Result of a single URL import, for the toast. */
export type UrlImport = {
	/**  `"link"` (a bookmark) or `"media"` (a downloaded file). */
	kind: string,
	/**  Display title — the page title, or the media filename. */
	title: string,
	/**  Short host, e.g. `x.com`. */
	host: string,
	/**
	 *  The asset was already in the library (a link with the same URL, or media
	 *  with identical content).
	 */
	duplicate: boolean,
};

export type WatchedFolder = {
	id: string,
	path: string,
	/**  Library folder new files import into; None = library root. */
	folder_id: string | null,
	auto_import: boolean,
	/**  Unix ms of the last reconciliation pass; None = never scanned. */
	last_scanned_at: number | null,
	/**  Unix ms. */
	created_at: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

