import type { AppError } from "@/lib/bindings";
import { T } from "@/lib/text";

/**
 * The typed IPC error. `AppError` is generated by tauri-specta from the Rust
 * enum (`src-tauri/src/error.rs`) into `@/lib/bindings`; this re-export gives it
 * a stable, intention-revealing name and a place to hang frontend helpers.
 *
 * Branch on the stable `code` for UI/retry decisions; `detail` is for display
 * and logging only.
 */
export type CommandError = AppError;

/** Narrow an unknown thrown value (e.g. from a rejected `invoke`) to a CommandError. */
export function isCommandError(error: unknown): error is CommandError {
	return (
		typeof error === "object" &&
		error !== null &&
		"code" in error &&
		typeof (error as { code: unknown }).code === "string"
	);
}

/**
 * Human-readable (Chinese) message for any thrown value — the standard
 * `onError` → `toast.error(describeError(err))` path.
 *
 * Known codes map to fixed copy in `T.errors`; the Rust-provided `detail`
 * is appended for the variants where it helps the user act.
 */
export function describeError(error: unknown): string {
	if (isCommandError(error)) {
		const summary = T.errors[error.code] ?? T.errors.unknown;
		if ("detail" in error && typeof error.detail === "string") {
			// Detail is user-displayable per the error model, but only add it
			// where it carries actionable context (paths, versions).
			if (error.code === "LibraryIncompatible" || error.code === "Conflict") {
				return T.errors.withDetail(summary, error.detail);
			}
		}
		return summary;
	}
	if (error instanceof Error && error.message) {
		return T.errors.withDetail(T.errors.unknown, error.message);
	}
	return T.errors.unknown;
}
