/**
 * All user-facing copy (incl. aria-labels, toasts, confirmations) lives here —
 * components never hardcode display strings.
 *
 * Conventions:
 * - Grouped by domain; interpolation always via functions
 * - Error-code → copy mapping lives in the `errors` group (see `describeError`)
 * - Split by domain once this file outgrows ~300 lines
 */

/** "3 items" / "1 item" — naive pluralizer for regular nouns. */
const counted = (n: number, noun: string) =>
	`${n} ${n === 1 ? noun : `${noun}s`}`;

export const T = {
	app: {
		name: "yAssets",
	},
	common: {
		cancel: "Cancel",
		confirm: "Confirm",
		remove: "Remove",
		loading: "Loading…",
	},
	preferences: {
		title: "Preferences",
		open: "Preferences…",
		navGeneral: "General",
		sectionAppearance: "Appearance",
		theme: "Theme",
		themeLight: "Light",
		themeDark: "Dark",
		themeSystem: "System",
		sectionUpdates: "Updates",
		checkUpdates: "Check for Updates",
		checkingUpdates: "Checking…",
		upToDate: "You're on the latest version",
		updateFailed: "Update check failed",
	},
	updates: {
		available: (version: string) => `yAssets ${version} is available`,
		installAction: "Install & Restart",
		installing: "Downloading update…",
		failed: "Update failed — try again from Preferences",
	},
	welcome: {
		tagline: "Local-first asset library",
		createLibrary: "New Library",
		openLibrary: "Open Library",
		pickCreateTitle: "Choose where to create the library (empty folder)",
		pickOpenTitle: "Choose a library folder",
		recentTitle: "Recent",
		recentEmpty: "No Recent Libraries",
		recentEmptyHint: "Libraries you create or open will show up here.",
		missingBadge: "Moved or deleted",
		removeRecent: "Remove from list",
		opening: "Opening…",
	},
	toolbar: {
		back: "Back",
		forward: "Forward",
		searchPlaceholder: "Search",
		zoom: "Thumbnail size",
		zoomIn: "Zoom in",
		zoomOut: "Zoom out",
	},
	sidebar: {
		all: "All",
		uncategorized: "Uncategorized",
		untagged: "Untagged",
		recent: "Recently Added",
		trash: "Trash",
		foldersTitle: "Folders",
		newFolder: "New Folder",
		tagsTitle: "Tags",
		filterPlaceholder: "Filter…",
		collapse: "Collapse",
		expand: "Expand",
		switcher: {
			openOther: "Open Other Library…",
			createNew: "New Library…",
			closeCurrent: "Close Current Library",
			recentGroup: "Recent",
		},
	},
	smartFolders: {
		title: "Smart Folders",
		create: "New Smart Folder",
		editTitle: "Edit Smart Folder",
		nameLabel: "Name",
		namePlaceholder: "Smart folder name",
		matchLabel: "Match",
		matchAll: "All conditions",
		matchAny: "Any condition",
		conditionsLabel: "Conditions",
		addCondition: "Add Condition",
		removeCondition: "Remove condition",
		emptyConditions: "No conditions — matches every asset.",
		fields: {
			ext: "Format is",
			name_contains: "Name contains",
			rating_at_least: "Rating at least",
			hue: "Color is",
			has_tag: "Has tag",
			added_within_days: "Added within",
		},
		extPlaceholder: "png, jpg, mp4…",
		keywordPlaceholder: "keyword",
		daysSuffix: "days",
		noTagsAvailable: "No tags yet",
		saveAction: "Save",
		createAction: "Create",
		menuEdit: "Edit",
		menuDelete: "Delete",
		deleteTitle: (name: string) => `Delete smart folder “${name}”?`,
		deleteDesc: "Assets are not affected — only the saved rules are removed.",
		deleteAction: "Delete",
	},
	folderDialog: {
		createTitle: "New Folder",
		createChildTitle: (parent: string) => `New folder in “${parent}”`,
		renameTitle: "Rename Folder",
		namePlaceholder: "Folder name",
		createAction: "Create",
		renameAction: "Rename",
	},
	folderMenu: {
		newSubfolder: "New Subfolder",
		rename: "Rename",
		delete: "Delete Folder",
		deleteTitle: (name: string) => `Delete folder “${name}”?`,
		deleteDesc:
			"Its subfolders will be deleted too. Assets are kept and return to Uncategorized.",
		deleteAction: "Delete",
	},
	assetMenu: {
		addToFolder: "Add to Folder",
		noFolders: "No folders yet",
		removeFromFolder: "Remove from This Folder",
		reveal: "Reveal in Finder",
		findSimilar: "Find Similar",
		regenerateCover: "Regenerate Cover",
		export: "Export",
		trash: "Move to Trash",
		restore: "Restore",
		deleteForever: "Delete Permanently…",
	},
	trashUi: {
		emptyTrash: "Empty Trash",
		itemsInTrash: (n: number) => `${counted(n, "item")} in Trash`,
		confirmEmptyTitle: "Empty Trash?",
		confirmEmptyDesc:
			"All assets in the Trash will be permanently deleted. This cannot be undone.",
		confirmDeleteTitle: "Delete Permanently?",
		confirmDeleteDesc: (n: number) =>
			n > 1
				? `${n} assets will be permanently deleted. This cannot be undone.`
				: "This asset will be permanently deleted. This cannot be undone.",
		confirmAction: "Delete Permanently",
	},
	viewTitles: {
		all: "All",
		uncategorized: "Uncategorized",
		untagged: "Untagged",
		recent: "Recently Added",
		trash: "Trash",
		folderFallback: "Folder",
		tagFallback: "Tag",
		color: "By Color",
		similar: "Similar Assets",
		smartFallback: "Smart Folder",
		searchPrefix: (q: string) => `Search: ${q}`,
	},
	folderStrip: {
		subfolders: (n: number) => `${n === 1 ? "Subfolder" : "Subfolders"} (${n})`,
	},
	tags: {
		addPlaceholder: "Search or create a tag…",
		newTag: "New Tag",
		createEntry: (name: string) => `Create “${name}”`,
		noTags: "No tags yet",
		removeFromAsset: "Remove this tag",
		rename: "Rename",
		editColor: "Set Color",
		delete: "Delete Tag",
		deleteTitle: (name: string) => `Delete tag “${name}”?`,
		deleteDesc: "Assets are kept — only the tag itself is removed.",
		deleteAction: "Delete",
		editTitle: "Edit Tag",
		nameLabel: "Name",
		colorLabel: "Color",
		colorNone: "None",
		saveAction: "Save",
	},
	/** Per-view empty states — title + supporting hint (unified EmptyState). */
	gridEmpty: {
		noSearchResult: {
			title: "No Results",
			hint: "Nothing matches your search. Try different keywords.",
		},
		folderEmpty: {
			title: "No Files Here",
			hint: "Drop files here, or drag cards from other views into this folder.",
		},
		uncategorizedEmpty: {
			title: "All Organized",
			hint: "Every asset belongs to at least one folder.",
		},
		untaggedEmpty: {
			title: "No Untagged Assets",
			hint: "Every asset has at least one tag.",
		},
		tagEmpty: {
			title: "No Assets with This Tag",
			hint: "Tag assets from the inspector and they will show up here.",
		},
		colorEmpty: {
			title: "No Assets in This Color",
			hint: "Try another swatch, or clear the color filter.",
		},
		recentEmpty: {
			title: "Nothing Recent",
			hint: "Assets imported in the last 30 days show up here.",
		},
		trashEmpty: {
			title: "Trash is Empty",
			hint: "Deleted assets are kept here until you empty the trash.",
		},
		similarEmpty: {
			title: "No Similar Assets",
			hint: "Nothing else looks like this yet — or its visual fingerprint hasn't been computed.",
		},
		smartEmpty: {
			title: "No Matches",
			hint: "No assets match this smart folder's rules yet.",
		},
	},
	grid: {
		emptyTitle: "Drop Files Here",
		emptyHint: "Drag in files or folders — or paste from the clipboard.",
	},
	export: {
		pickTitle: "Choose export destination",
		action: "Export",
		actionN: (n: number) => `Export (${n})`,
		done: (n: number) => `Exported ${counted(n, "item")}`,
		empty: "Nothing to export",
	},
	colorFilter: {
		label: "Color",
		all: "All Colors",
		neutral: "Black & White",
	},
	import: {
		started: "Preparing import…",
		discovering: (total: number) => `Scanning files… (${total} found)`,
		progress: (done: number, total: number) => `Importing ${done}/${total}…`,
		finished: (imported: number, skipped: number) =>
			skipped > 0
				? `Imported ${counted(imported, "item")}, skipped ${skipped} duplicate${skipped === 1 ? "" : "s"}`
				: `Imported ${counted(imported, "item")}`,
		finishedWithFailures: (imported: number, skipped: number, failed: number) =>
			`Imported ${imported}, failed ${failed}${skipped > 0 ? `, skipped ${skipped}` : ""}`,
		cancelled: (imported: number) => `Import cancelled (${imported} completed)`,
		dropHint: "Drop to import into this library",
		importFiles: "Import Files",
		importFolder: "Import Folder",
		pasteEmpty: "Clipboard has nothing importable",
	},
	duplicatesCenter: {
		open: "Find Duplicates…",
		title: "Duplicates",
		scanning: "Scanning library…",
		empty: {
			title: "No Duplicates",
			hint: "Every asset in this library is unique — nice and tidy.",
		},
		exactSection: (n: number) => `Exact duplicates · ${counted(n, "group")}`,
		exactHint:
			"Byte-identical files. Cleaning keeps the earliest import and trashes the rest.",
		visualSection: (n: number) => `Visually similar · ${counted(n, "group")}`,
		visualHint: "Look-alikes across different files — compare before deciding.",
		filesMeta: (n: number, size: string) => `${counted(n, "file")} · ${size}`,
		trashOthers: (n: number) => `Trash ${counted(n, "duplicate")}`,
		trashAll: (n: number) => `Trash all ${counted(n, "duplicate")}`,
		compare: "Compare",
		rescan: "Rescan",
	},
	duplicates: {
		title: (n: number) => `Duplicate Files (${n})`,
		hint: "These files already exist in your library with identical content.",
		existing: "Existing",
		incoming: "Imported",
		useExisting: "Use existing files",
		keepBoth: "Keep both",
		importAction: "Import",
	},
	inspector: {
		emptyTitle: "No Selection",
		emptyHint: "Select an asset to view and edit its details.",
		notePlaceholder: "Notes…",
		urlPlaceholder: "http://",
		openLink: "Open link",
		ratingLabel: "Rating",
		starLabel: (n: number) => counted(n, "star"),
		foldersLabel: "Folders",
		addToFolder: "Add to Folder",
		removeFromThisFolder: "Remove from this folder",
		infoTitle: "Properties",
		infoDimensions: "Dimensions",
		infoSize: "Size",
		infoFormat: "Type",
		infoImported: "Date Imported",
		infoCreated: "Date Created",
		infoModified: "Date Modified",
		infoSource: "Source",
		exportAction: "Export",
		exportSoon: "Coming soon",
		itemCount: (n: number) => counted(n, "item"),
		// Folder info panel
		folderItems: "Items",
		folderDescPlaceholder: "Add a description…",
	},
	drag: {
		count: (n: number) => counted(n, "item"),
	},
	multi: {
		title: (n: number) => `${n} selected`,
		trash: (n: number) => `Move to Trash (${n})`,
		restore: (n: number) => `Restore (${n})`,
	},
	video: {
		coverUpdating: "Extracting frame…",
		coverDone: "Cover updated",
		coverFailed: "Couldn't extract a frame from this video",
	},
	preview: {
		close: "Close preview",
		prev: "Previous",
		next: "Next",
		counter: (current: number, total: number) => `${current} / ${total}`,
		zoomIn: "Zoom in",
		zoomOut: "Zoom out",
		zoomFit: "Fit to window",
		zoomActual: "Actual size (100%)",
		textTruncated: "Showing the first 1 MB of this file.",
		textError: "Couldn't read this file.",
	},
	errorPage: {
		title: "Something Went Wrong",
		hint: "The interface hit an unexpected error. Go back home to keep working — if it persists, reload the app.",
		goHome: "Back to Home",
		reload: "Reload App",
		detailsLabel: "Error details",
	},
	errors: {
		NotFound: "Target file or folder not found",
		Io: "File read/write failed",
		Db: "Database error",
		NoLibraryOpen: "No library is open",
		LibraryIncompatible:
			"Not a valid library folder, or it was created by a newer version of the app",
		Conflict: "The operation conflicts with the current state",
		Internal: "An internal error occurred",
		unknown: "An unknown error occurred",
		withDetail: (summary: string, detail: string) => `${summary} (${detail})`,
	},
} as const;
