//! The agent surface's data layer — one implementation, two façades.
//!
//! Both the REST routes (`super::routes`) and the MCP tools (`super::mcp`) call
//! these functions, so the two can never drift apart. Everything reuses the
//! command cores (`commands::assets::list_page`, `commands::folders::all_folders_in`,
//! …) rather than hand-rolling SQL — an agent sees exactly what the UI sees.

use std::collections::HashMap;

use tauri::Manager;

use super::dto::{
    check_batch, AssetDetailRow, AssetIdsRequest, AssetRow, AuditRow, CreateFolderRequest,
    CreateSmartFolderRequest, CreateTagRequest, DuplicatesResponse, FolderAssetsRequest, FolderRow,
    FolderStatsRow, Includes, RateAssetsRequest, SearchRequest, SearchResponse, SmartFolderRow,
    StatsRow, TagAssetsRequest, TagRow, TagRowWithCount, UpdateAssetRequest, WriteResult,
};
use crate::error::{AppError, AppResult};
use crate::library::Library;
use crate::state::AppState;

/// Cap on the original bytes an agent may pull in one request. Thumbnails are
/// the intended way to look at an asset; the full file is an escape hatch, and a
/// 200 MB PSD has no business being inlined into a model's context.
pub const MAX_FILE_BYTES: u64 = 20 * 1024 * 1024;

/// Ids are opaque, generated by us: 10-32 chars of lowercase alphanumerics.
/// Validating before touching the filesystem means no request can ever build a
/// path segment — the same boundary `media_protocol` relies on.
pub fn is_valid_id(id: &str) -> bool {
    (10..=32).contains(&id.len())
        && id
            .bytes()
            .all(|b| b.is_ascii_digit() || b.is_ascii_lowercase())
}

fn library<R: tauri::Runtime>(app: &tauri::AppHandle<R>) -> AppResult<std::sync::Arc<Library>> {
    app.state::<AppState>().current_library()
}

/// Identity + capability probe. No absolute paths: the library is named, never
/// located.
pub fn info<R: tauri::Runtime>(app: &tauri::AppHandle<R>) -> serde_json::Value {
    let open = library(app).ok();
    serde_json::json!({
        "app": "yAssets",
        "version": env!("CARGO_PKG_VERSION"),
        "apiVersion": super::AGENT_API_VERSION,
        "readOnly": false,
        "libraryOpen": open.is_some(),
        "libraryName": open.map(|lib| lib.info().name),
        "capabilities": [
            "search", "detail", "similar", "duplicates",
            "folders", "tags", "smartFolders", "stats",
            "thumb", "file", "mcp",
            "write", "dryRun", "audit",
        ],
        "limits": {
            "maxSearchLimit": super::dto::MAX_LIMIT,
            "maxFileBytes": MAX_FILE_BYTES,
            "maxBatch": super::dto::MAX_BATCH,
        },
        // Deliberately absent, now and later — see docs/agent-api.md.
        "notPermitted": [
            "permanent deletion", "emptying the trash", "orphan cleanup",
            "vacuum", "switching libraries", "importing from disk",
            "exporting to disk",
        ],
    })
}

/// Attach the requested joins to a page of rows. One chunked query per join
/// rather than per row — a 200-row page must not become 400 queries.
fn hydrate(
    conn: &rusqlite::Connection,
    rows: &mut [AssetRow],
    includes: Includes,
) -> AppResult<()> {
    if rows.is_empty() || (!includes.tags && !includes.folders) {
        return Ok(());
    }
    let ids: Vec<String> = rows.iter().map(|row| row.id.clone()).collect();

    if includes.tags {
        let mut by_asset: HashMap<String, Vec<TagRow>> = HashMap::new();
        for chunk in ids.chunks(400) {
            let placeholders = vec!["?"; chunk.len()].join(",");
            let sql = format!(
                "SELECT at.asset_id, t.id, t.name, t.color
                   FROM asset_tags at JOIN tags t ON t.id = at.tag_id
                  WHERE at.asset_id IN ({placeholders})
                  ORDER BY t.name COLLATE NOCASE"
            );
            let mut stmt = conn.prepare(&sql)?;
            let pairs = stmt
                .query_map(rusqlite::params_from_iter(chunk.iter()), |row| {
                    Ok((
                        row.get::<_, String>(0)?,
                        TagRow {
                            id: row.get(1)?,
                            name: row.get(2)?,
                            color: row.get(3)?,
                        },
                    ))
                })?
                .collect::<rusqlite::Result<Vec<_>>>()?;
            for (asset_id, tag) in pairs {
                by_asset.entry(asset_id).or_default().push(tag);
            }
        }
        for row in rows.iter_mut() {
            row.tags = Some(by_asset.remove(&row.id).unwrap_or_default());
        }
    }

    if includes.folders {
        let mut by_asset: HashMap<String, Vec<String>> = HashMap::new();
        for chunk in ids.chunks(400) {
            let placeholders = vec!["?"; chunk.len()].join(",");
            let sql = format!(
                "SELECT asset_id, folder_id FROM asset_folders
                  WHERE asset_id IN ({placeholders})"
            );
            let mut stmt = conn.prepare(&sql)?;
            let pairs = stmt
                .query_map(rusqlite::params_from_iter(chunk.iter()), |row| {
                    Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
                })?
                .collect::<rusqlite::Result<Vec<_>>>()?;
            for (asset_id, folder_id) in pairs {
                by_asset.entry(asset_id).or_default().push(folder_id);
            }
        }
        for row in rows.iter_mut() {
            row.folder_ids = Some(by_asset.remove(&row.id).unwrap_or_default());
        }
    }
    Ok(())
}

pub async fn search<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: SearchRequest,
) -> AppResult<SearchResponse> {
    let lib = library(app)?;
    let query = request.to_query()?;
    let includes = request.includes();
    let offset = request.effective_offset();
    let limit = request.effective_limit();
    lib.read(move |conn| {
        let page = crate::commands::assets::list_page(conn, &query)?;
        let mut rows: Vec<AssetRow> = page.items.into_iter().map(AssetRow::from_summary).collect();
        hydrate(conn, &mut rows, includes)?;
        Ok(SearchResponse::new(page.total, offset, limit, rows))
    })
    .await
}

pub async fn detail<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    id: &str,
) -> AppResult<AssetDetailRow> {
    let lib = library(app)?;
    let id = id.to_string();
    lib.read(move |conn| {
        crate::commands::assets::detail_by_id(conn, &id).map(AssetDetailRow::from_detail)
    })
    .await
}

pub async fn similar<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    id: &str,
    max_distance: u32,
) -> AppResult<Vec<AssetRow>> {
    let lib = library(app)?;
    let id = id.to_string();
    let max_distance = max_distance.min(crate::commands::assets::MAX_SIMILAR_DISTANCE);
    lib.read(move |conn| {
        Ok(
            crate::commands::assets::similar_in(conn, &id, max_distance)?
                .into_iter()
                .map(AssetRow::from_summary)
                .collect(),
        )
    })
    .await
}

pub async fn folders<R: tauri::Runtime>(app: &tauri::AppHandle<R>) -> AppResult<Vec<FolderRow>> {
    let lib = library(app)?;
    lib.read(|conn| {
        Ok(crate::commands::folders::all_folders_in(conn)?
            .into_iter()
            .map(FolderRow::from)
            .collect())
    })
    .await
}

pub async fn folder_stats<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    folder_id: &str,
) -> AppResult<FolderStatsRow> {
    let lib = library(app)?;
    let folder_id = folder_id.to_string();
    lib.read(move |conn| {
        // The command reports zeroes for an unknown id; an agent needs to know
        // it aimed at nothing, so confirm the folder exists first.
        let exists: bool = conn.query_row(
            "SELECT EXISTS (SELECT 1 FROM folders WHERE id = ?1)",
            [folder_id.as_str()],
            |row| row.get(0),
        )?;
        if !exists {
            return Err(AppError::NotFound(format!("folder {folder_id}")));
        }
        Ok(FolderStatsRow::from(
            crate::commands::folders::compute_folder_stats(conn, &folder_id)?,
        ))
    })
    .await
}

pub async fn tags<R: tauri::Runtime>(app: &tauri::AppHandle<R>) -> AppResult<Vec<TagRowWithCount>> {
    let lib = library(app)?;
    lib.read(|conn| {
        Ok(crate::commands::tags::all_tags_in(conn)?
            .into_iter()
            .map(TagRowWithCount::from)
            .collect())
    })
    .await
}

pub async fn smart_folders<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
) -> AppResult<Vec<SmartFolderRow>> {
    let lib = library(app)?;
    lib.read(|conn| {
        Ok(crate::commands::smart_folders::all_smart_folders_in(conn)?
            .into_iter()
            .map(SmartFolderRow::from)
            .collect())
    })
    .await
}

pub async fn stats<R: tauri::Runtime>(app: &tauri::AppHandle<R>) -> AppResult<StatsRow> {
    let lib = library(app)?;
    lib.read(|conn| {
        Ok(StatsRow::from(crate::commands::library::library_stats_in(
            conn,
        )?))
    })
    .await
}

/// A full-library duplicate scan is O(n²) over fingerprints. Cheap enough to
/// offer, expensive enough that an agent in a retry loop shouldn't be able to
/// pin a core. Enforced here rather than in the route so the MCP tool is bound
/// by the same window.
pub const DUPLICATE_SCAN_INTERVAL: std::time::Duration = std::time::Duration::from_secs(30);
static LAST_DUPLICATE_SCAN: std::sync::Mutex<Option<std::time::Instant>> =
    std::sync::Mutex::new(None);

fn claim_duplicate_scan() -> AppResult<()> {
    let mut last = match LAST_DUPLICATE_SCAN.lock() {
        Ok(guard) => guard,
        Err(poisoned) => poisoned.into_inner(),
    };
    let now = std::time::Instant::now();
    if let Some(previous) = *last {
        if now.duration_since(previous) < DUPLICATE_SCAN_INTERVAL {
            return Err(AppError::RateLimited(format!(
                "a duplicate scan runs at most once every {}s",
                DUPLICATE_SCAN_INTERVAL.as_secs()
            )));
        }
    }
    *last = Some(now);
    Ok(())
}

pub async fn duplicates<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
) -> AppResult<DuplicatesResponse> {
    let lib = library(app)?;
    claim_duplicate_scan()?;
    lib.read(|conn| {
        let scan = crate::commands::duplicates::scan_duplicates_in(conn)?;
        let map = |groups: Vec<Vec<crate::commands::assets::AssetSummary>>| {
            groups
                .into_iter()
                .map(|group| group.into_iter().map(AssetRow::from_summary).collect())
                .collect()
        };
        Ok(DuplicatesResponse {
            exact: map(scan.exact),
            visual: map(scan.visual),
        })
    })
    .await
}

/// The cached WebP thumbnail. Preferred over `file_bytes` for "what is this?"
/// questions: already downscaled, always the same format, a few KB.
pub async fn thumb_bytes<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    id: &str,
) -> AppResult<Vec<u8>> {
    if !is_valid_id(id) {
        return Err(AppError::NotFound(format!("asset {id}")));
    }
    let lib = library(app)?;
    let path = lib.thumb_path(id);
    tokio::fs::read(&path)
        .await
        .map_err(|_| AppError::NotFound(format!("no thumbnail for asset {id}")))
}

/// The managed original, with its recorded MIME type. Refuses anything over
/// [`MAX_FILE_BYTES`] instead of streaming it into a model's context.
pub async fn file_bytes<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    id: &str,
) -> AppResult<(Vec<u8>, String)> {
    if !is_valid_id(id) {
        return Err(AppError::NotFound(format!("asset {id}")));
    }
    let lib = library(app)?;
    let lookup = lib.clone();
    let asset_id = id.to_string();
    let (rel_path, mime, size) = lookup
        .read(move |conn| {
            conn.query_row(
                "SELECT rel_path, mime, size FROM assets WHERE id = ?1",
                [asset_id.as_str()],
                |row| {
                    Ok((
                        row.get::<_, String>(0)?,
                        row.get::<_, Option<String>>(1)?,
                        row.get::<_, i64>(2)?,
                    ))
                },
            )
            .map_err(|err| match err {
                rusqlite::Error::QueryReturnedNoRows => {
                    AppError::NotFound(format!("asset {asset_id}"))
                }
                other => other.into(),
            })
        })
        .await?;
    if size as u64 > MAX_FILE_BYTES {
        return Err(AppError::Conflict(format!(
            "asset is {size} bytes, over the {MAX_FILE_BYTES}-byte limit — \
             fetch its thumbnail instead"
        )));
    }
    let bytes = tokio::fs::read(lib.resolve_rel(&rel_path))
        .await
        .map_err(|_| AppError::NotFound(format!("file missing for asset {id}")))?;
    Ok((
        bytes,
        mime.unwrap_or_else(|| "application/octet-stream".into()),
    ))
}

// ------------------------------------------------------------------ writes ---

/// How many target names a `WriteResult` carries. Enough to recognize the set,
/// few enough to stay out of the way.
const SAMPLE_SIZE: usize = 5;

/// Which side of the trash a batch is aiming at.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TargetState {
    Alive,
    Trashed,
}

/// Count and name the ids that actually resolve. Run before every write so a
/// dry run and the real thing agree on what "the target set" means, and so a
/// batch of stale ids reports 0 instead of silently doing nothing.
fn resolve_targets(
    conn: &rusqlite::Connection,
    asset_ids: &[String],
    state: TargetState,
) -> AppResult<(u32, Vec<String>)> {
    let deleted = match state {
        TargetState::Alive => "deleted_at IS NULL",
        TargetState::Trashed => "deleted_at IS NOT NULL",
    };
    let placeholders = vec!["?"; asset_ids.len()].join(",");
    let sql = format!(
        "SELECT name FROM assets
          WHERE {deleted} AND id IN ({placeholders})
          ORDER BY name COLLATE NOCASE"
    );
    let mut stmt = conn.prepare(&sql)?;
    let names = stmt
        .query_map(rusqlite::params_from_iter(asset_ids.iter()), |row| {
            row.get::<_, String>(0)
        })?
        .collect::<rusqlite::Result<Vec<_>>>()?;
    let total = names.len() as u32;
    Ok((total, names.into_iter().take(SAMPLE_SIZE).collect()))
}

/// Append one audit row. Best-effort by design: a failure to record must never
/// turn a successful write into an error, so callers ignore the result and the
/// problem shows up in the log instead.
fn audit_in(
    conn: &rusqlite::Connection,
    tool: &str,
    params: &serde_json::Value,
    affected: u32,
    ok: bool,
) {
    let outcome = conn.execute(
        "INSERT INTO agent_audit (id, at, tool, params_json, affected, ok)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
        rusqlite::params![
            crate::library::new_id(),
            crate::library::now_ms(),
            tool,
            params.to_string(),
            affected,
            ok as i64,
        ],
    );
    if let Err(err) = outcome {
        log::warn!("could not record the agent audit row for {tool}: {err}");
    }
}

/// Run a mutation under the writer lock, record it, and tell the UI.
///
/// The audit row is written inside the same lock hold as the mutation, so a
/// successful write is always accompanied by its record. The event is what keeps
/// open views honest — a server-side write bypasses the frontend's mutation
/// layer entirely, so without it every grid would keep showing stale rows.
async fn audited<R: tauri::Runtime, T: Send + 'static>(
    app: &tauri::AppHandle<R>,
    tool: &'static str,
    params: serde_json::Value,
    write: impl FnOnce(&mut rusqlite::Connection) -> AppResult<(T, u32)> + Send + 'static,
) -> AppResult<T> {
    let lib = library(app)?;
    let outcome = lib
        .write(move |conn| {
            let result = write(conn);
            match &result {
                Ok((_, affected)) => audit_in(conn, tool, &params, *affected, true),
                Err(_) => audit_in(conn, tool, &params, 0, false),
            }
            result
        })
        .await?;
    let (value, affected) = outcome;
    if affected > 0 {
        use tauri_specta::Event;
        let event = crate::events::AgentMutated {
            tool: tool.to_string(),
            affected,
        };
        if let Err(err) = event.emit(app) {
            log::warn!("could not notify the UI of an agent write: {err}");
        }
    }
    Ok(value)
}

/// Shared skeleton for the batch writes: validate, resolve the target set, stop
/// there on a dry run, otherwise mutate under audit.
async fn batch_write<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    tool: &'static str,
    params: serde_json::Value,
    asset_ids: Vec<String>,
    dry_run: bool,
    state: TargetState,
    write: impl FnOnce(&mut rusqlite::Connection, &[String]) -> AppResult<u32> + Send + 'static,
) -> AppResult<WriteResult> {
    check_batch(&asset_ids)?;
    let lib = library(app)?;
    let (targets, sample) = {
        let ids = asset_ids.clone();
        lib.read(move |conn| resolve_targets(conn, &ids, state))
            .await?
    };
    if dry_run {
        return Ok(WriteResult {
            dry_run: true,
            targets,
            affected: 0,
            sample,
        });
    }
    let affected = audited(app, tool, params, move |conn| {
        let affected = write(conn, &asset_ids)?;
        Ok((affected, affected))
    })
    .await?;
    Ok(WriteResult {
        dry_run: false,
        targets,
        affected,
        sample,
    })
}

pub async fn tag_assets<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: TagAssetsRequest,
) -> AppResult<WriteResult> {
    if !request.has_tags() {
        return Err(AppError::Conflict(
            "pass `tags` (names, created on demand) and/or `tagIds`".into(),
        ));
    }
    let params = serde_json::json!({
        "assetIds": request.asset_ids.len(),
        "tags": request.tags,
        "tagIds": request.tag_ids,
    });
    let names = request.tags.clone();
    let mut tag_ids = request.tag_ids.clone();
    batch_write(
        app,
        "tag_assets",
        params,
        request.asset_ids,
        request.dry_run,
        TargetState::Alive,
        move |conn, asset_ids| {
            // Names first: create-or-get resolves each to an id in the same
            // writer hold, so a fresh vocabulary lands atomically with its use.
            for name in names.iter().filter(|name| !name.trim().is_empty()) {
                tag_ids.push(crate::commands::tags::create_or_get_tag_in(conn, name, None)?.id);
            }
            crate::commands::tags::add_tags_in(conn, asset_ids, &tag_ids)
        },
    )
    .await
}

pub async fn untag_assets<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: TagAssetsRequest,
) -> AppResult<WriteResult> {
    if !request.has_tags() {
        return Err(AppError::Conflict(
            "pass `tags` (existing names) and/or `tagIds`".into(),
        ));
    }
    let params = serde_json::json!({
        "assetIds": request.asset_ids.len(),
        "tags": request.tags,
        "tagIds": request.tag_ids,
    });
    let names = request.tags.clone();
    let mut tag_ids = request.tag_ids.clone();
    batch_write(
        app,
        "untag_assets",
        params,
        request.asset_ids,
        request.dry_run,
        TargetState::Alive,
        move |conn, asset_ids| {
            // Removing must never create a tag: an unknown name is simply a
            // no-op, not a new empty tag.
            for name in names.iter().filter(|name| !name.trim().is_empty()) {
                if let Ok(id) = conn.query_row(
                    "SELECT id FROM tags WHERE name = ?1 COLLATE NOCASE",
                    [name.trim()],
                    |row| row.get::<_, String>(0),
                ) {
                    tag_ids.push(id);
                }
            }
            if tag_ids.is_empty() {
                return Ok(0);
            }
            crate::commands::tags::remove_tags_in(conn, asset_ids, &tag_ids)
        },
    )
    .await
}

pub async fn add_to_folder<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: FolderAssetsRequest,
) -> AppResult<WriteResult> {
    let folder_id = request.folder_id.clone();
    let params = serde_json::json!({
        "assetIds": request.asset_ids.len(),
        "folderId": folder_id,
    });
    batch_write(
        app,
        "add_to_folder",
        params,
        request.asset_ids,
        request.dry_run,
        TargetState::Alive,
        move |conn, asset_ids| {
            crate::commands::folders::add_assets_to_folder_in(conn, asset_ids, &folder_id)
        },
    )
    .await
}

pub async fn remove_from_folder<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: FolderAssetsRequest,
) -> AppResult<WriteResult> {
    let folder_id = request.folder_id.clone();
    let params = serde_json::json!({
        "assetIds": request.asset_ids.len(),
        "folderId": folder_id,
    });
    batch_write(
        app,
        "remove_from_folder",
        params,
        request.asset_ids,
        request.dry_run,
        TargetState::Alive,
        move |conn, asset_ids| {
            crate::commands::folders::remove_assets_from_folder_in(conn, asset_ids, &folder_id)
        },
    )
    .await
}

pub async fn rate_assets<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: RateAssetsRequest,
) -> AppResult<WriteResult> {
    if request.rating > 5 {
        return Err(AppError::Conflict("rating must be 0-5".into()));
    }
    let rating = request.rating;
    let params = serde_json::json!({
        "assetIds": request.asset_ids.len(),
        "rating": rating,
    });
    batch_write(
        app,
        "rate_assets",
        params,
        request.asset_ids,
        request.dry_run,
        TargetState::Alive,
        move |conn, asset_ids| crate::commands::assets::set_rating_in(conn, asset_ids, rating),
    )
    .await
}

pub async fn trash_assets<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: AssetIdsRequest,
) -> AppResult<WriteResult> {
    let params = serde_json::json!({ "assetIds": request.asset_ids.len() });
    batch_write(
        app,
        "trash_assets",
        params,
        request.asset_ids,
        request.dry_run,
        TargetState::Alive,
        move |conn, asset_ids| crate::commands::trash::trash_in(conn, asset_ids),
    )
    .await
}

pub async fn restore_assets<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: AssetIdsRequest,
) -> AppResult<WriteResult> {
    let params = serde_json::json!({ "assetIds": request.asset_ids.len() });
    batch_write(
        app,
        "restore_assets",
        params,
        request.asset_ids,
        request.dry_run,
        // Restore targets rows that are IN the trash — resolving against alive
        // assets would report 0 targets for a perfectly good request.
        TargetState::Trashed,
        move |conn, asset_ids| crate::commands::trash::restore_in(conn, asset_ids),
    )
    .await
}

pub async fn create_folder<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: CreateFolderRequest,
) -> AppResult<FolderRow> {
    let params = serde_json::json!({ "name": request.name, "parentId": request.parent_id });
    audited(app, "create_folder", params, move |conn| {
        let folder = crate::commands::folders::create_folder_in(
            conn,
            &request.name,
            request.parent_id.as_deref(),
        )?;
        Ok((FolderRow::from(folder), 1))
    })
    .await
}

pub async fn create_tag<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: CreateTagRequest,
) -> AppResult<TagRowWithCount> {
    let params = serde_json::json!({ "name": request.name, "color": request.color });
    audited(app, "create_tag", params, move |conn| {
        let tag = crate::commands::tags::create_or_get_tag_in(
            conn,
            &request.name,
            request.color.as_deref(),
        )?;
        Ok((TagRowWithCount::from(tag), 1))
    })
    .await
}

pub async fn update_asset<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: UpdateAssetRequest,
) -> AppResult<AssetDetailRow> {
    if !is_valid_id(&request.id) {
        return Err(AppError::NotFound(format!("asset {}", request.id)));
    }
    if !request.touches_anything() {
        return Err(AppError::Conflict(
            "pass at least one of name, note, rating or url".into(),
        ));
    }
    let patch = request.to_patch();
    crate::commands::assets::validate_patch(&patch)?;
    // Record which fields were touched, not their values — a note can be long
    // and the audit log is for tracing intent, not for storing content twice.
    let fields: Vec<&str> = [
        request.name.is_some().then_some("name"),
        request.note.is_some().then_some("note"),
        request.rating.is_some().then_some("rating"),
        request.url.is_some().then_some("url"),
    ]
    .into_iter()
    .flatten()
    .collect();
    let params = serde_json::json!({ "id": request.id, "fields": fields });
    audited(app, "update_asset", params, move |conn| {
        let detail = crate::commands::assets::update_asset_in(conn, &request.id, &patch)?;
        Ok((AssetDetailRow::from_detail(detail), 1))
    })
    .await
}

pub async fn create_smart_folder<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: CreateSmartFolderRequest,
) -> AppResult<SmartFolderRow> {
    let params = serde_json::json!({ "name": request.name });
    audited(app, "create_smart_folder", params, move |conn| {
        let folder = crate::commands::smart_folders::create_smart_folder_in(
            conn,
            &request.name,
            request.rules,
        )?;
        Ok((SmartFolderRow::from(folder), 1))
    })
    .await
}

/// The write log, newest first — what the agent (or the user) actually changed.
pub async fn audit<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    limit: u32,
) -> AppResult<Vec<AuditRow>> {
    let lib = library(app)?;
    let limit = limit.clamp(1, 200);
    lib.read(move |conn| {
        let mut stmt = conn.prepare(
            "SELECT at, tool, params_json, affected, ok FROM agent_audit
              ORDER BY at DESC LIMIT ?1",
        )?;
        let rows = stmt
            .query_map([limit], |row| {
                Ok(AuditRow {
                    at: row.get::<_, i64>(0)?,
                    tool: row.get(1)?,
                    params: serde_json::from_str(&row.get::<_, String>(2)?)
                        .unwrap_or(serde_json::Value::Null),
                    affected: row.get::<_, i64>(3)? as u32,
                    ok: row.get::<_, i64>(4)? != 0,
                })
            })?
            .collect::<rusqlite::Result<Vec<_>>>()?;
        Ok(rows)
    })
    .await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn only_generated_ids_are_accepted() {
        assert!(is_valid_id("asset000000000000001"));
        assert!(!is_valid_id("short"));
        assert!(!is_valid_id("../../../etc/passwd"));
        assert!(
            !is_valid_id("ASSET000000000000001"),
            "uppercase is not ours"
        );
        assert!(!is_valid_id("asset-0000000000001"), "no punctuation");
        assert!(!is_valid_id(&"a".repeat(33)));
    }
}
