//! The agent surface's data layer — one implementation, two façades.
//!
//! Both the REST routes (`super::routes`) and the MCP tools (`super::mcp`) call
//! these functions, so the two can never drift apart. Everything reuses the
//! command cores (`commands::assets::list_page`, `commands::folders::all_folders_in`,
//! …) rather than hand-rolling SQL — an agent sees exactly what the UI sees.

use std::collections::HashMap;

use tauri::Manager;

use super::dto::{
    AssetDetailRow, AssetRow, DuplicatesResponse, FolderRow, FolderStatsRow, Includes,
    SearchRequest, SearchResponse, SmartFolderRow, StatsRow, TagRow, TagRowWithCount,
};
use crate::error::{AppError, AppResult};
use crate::library::Library;
use crate::state::AppState;

/// Cap on the original bytes an agent may pull in one request. Thumbnails are
/// the intended way to look at an asset; the full file is an escape hatch, and a
/// 200 MB PSD has no business being inlined into a model's context.
pub const MAX_FILE_BYTES: u64 = 20 * 1024 * 1024;

/// Ids are opaque, generated by us: 10-32 chars of lowercase alphanumerics.
/// Validating before touching the filesystem means no request can ever build a
/// path segment — the same boundary `media_protocol` relies on.
pub fn is_valid_id(id: &str) -> bool {
    (10..=32).contains(&id.len())
        && id
            .bytes()
            .all(|b| b.is_ascii_digit() || b.is_ascii_lowercase())
}

fn library<R: tauri::Runtime>(app: &tauri::AppHandle<R>) -> AppResult<std::sync::Arc<Library>> {
    app.state::<AppState>().current_library()
}

/// Identity + capability probe. No absolute paths: the library is named, never
/// located.
pub fn info<R: tauri::Runtime>(app: &tauri::AppHandle<R>) -> serde_json::Value {
    let open = library(app).ok();
    serde_json::json!({
        "app": "yAssets",
        "version": env!("CARGO_PKG_VERSION"),
        "apiVersion": super::AGENT_API_VERSION,
        "readOnly": true,
        "libraryOpen": open.is_some(),
        "libraryName": open.map(|lib| lib.info().name),
        "capabilities": [
            "search", "detail", "similar", "duplicates",
            "folders", "tags", "smartFolders", "stats",
            "thumb", "file", "mcp",
        ],
        "limits": {
            "maxSearchLimit": super::dto::MAX_LIMIT,
            "maxFileBytes": MAX_FILE_BYTES,
        },
    })
}

/// Attach the requested joins to a page of rows. One chunked query per join
/// rather than per row — a 200-row page must not become 400 queries.
fn hydrate(
    conn: &rusqlite::Connection,
    rows: &mut [AssetRow],
    includes: Includes,
) -> AppResult<()> {
    if rows.is_empty() || (!includes.tags && !includes.folders) {
        return Ok(());
    }
    let ids: Vec<String> = rows.iter().map(|row| row.id.clone()).collect();

    if includes.tags {
        let mut by_asset: HashMap<String, Vec<TagRow>> = HashMap::new();
        for chunk in ids.chunks(400) {
            let placeholders = vec!["?"; chunk.len()].join(",");
            let sql = format!(
                "SELECT at.asset_id, t.id, t.name, t.color
                   FROM asset_tags at JOIN tags t ON t.id = at.tag_id
                  WHERE at.asset_id IN ({placeholders})
                  ORDER BY t.name COLLATE NOCASE"
            );
            let mut stmt = conn.prepare(&sql)?;
            let pairs = stmt
                .query_map(rusqlite::params_from_iter(chunk.iter()), |row| {
                    Ok((
                        row.get::<_, String>(0)?,
                        TagRow {
                            id: row.get(1)?,
                            name: row.get(2)?,
                            color: row.get(3)?,
                        },
                    ))
                })?
                .collect::<rusqlite::Result<Vec<_>>>()?;
            for (asset_id, tag) in pairs {
                by_asset.entry(asset_id).or_default().push(tag);
            }
        }
        for row in rows.iter_mut() {
            row.tags = Some(by_asset.remove(&row.id).unwrap_or_default());
        }
    }

    if includes.folders {
        let mut by_asset: HashMap<String, Vec<String>> = HashMap::new();
        for chunk in ids.chunks(400) {
            let placeholders = vec!["?"; chunk.len()].join(",");
            let sql = format!(
                "SELECT asset_id, folder_id FROM asset_folders
                  WHERE asset_id IN ({placeholders})"
            );
            let mut stmt = conn.prepare(&sql)?;
            let pairs = stmt
                .query_map(rusqlite::params_from_iter(chunk.iter()), |row| {
                    Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
                })?
                .collect::<rusqlite::Result<Vec<_>>>()?;
            for (asset_id, folder_id) in pairs {
                by_asset.entry(asset_id).or_default().push(folder_id);
            }
        }
        for row in rows.iter_mut() {
            row.folder_ids = Some(by_asset.remove(&row.id).unwrap_or_default());
        }
    }
    Ok(())
}

pub async fn search<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    request: SearchRequest,
) -> AppResult<SearchResponse> {
    let lib = library(app)?;
    let query = request.to_query()?;
    let includes = request.includes();
    let offset = request.effective_offset();
    let limit = request.effective_limit();
    lib.read(move |conn| {
        let page = crate::commands::assets::list_page(conn, &query)?;
        let mut rows: Vec<AssetRow> = page.items.into_iter().map(AssetRow::from_summary).collect();
        hydrate(conn, &mut rows, includes)?;
        Ok(SearchResponse::new(page.total, offset, limit, rows))
    })
    .await
}

pub async fn detail<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    id: &str,
) -> AppResult<AssetDetailRow> {
    let lib = library(app)?;
    let id = id.to_string();
    lib.read(move |conn| {
        crate::commands::assets::detail_by_id(conn, &id).map(AssetDetailRow::from_detail)
    })
    .await
}

pub async fn similar<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    id: &str,
    max_distance: u32,
) -> AppResult<Vec<AssetRow>> {
    let lib = library(app)?;
    let id = id.to_string();
    let max_distance = max_distance.min(crate::commands::assets::MAX_SIMILAR_DISTANCE);
    lib.read(move |conn| {
        Ok(
            crate::commands::assets::similar_in(conn, &id, max_distance)?
                .into_iter()
                .map(AssetRow::from_summary)
                .collect(),
        )
    })
    .await
}

pub async fn folders<R: tauri::Runtime>(app: &tauri::AppHandle<R>) -> AppResult<Vec<FolderRow>> {
    let lib = library(app)?;
    lib.read(|conn| {
        Ok(crate::commands::folders::all_folders_in(conn)?
            .into_iter()
            .map(FolderRow::from)
            .collect())
    })
    .await
}

pub async fn folder_stats<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    folder_id: &str,
) -> AppResult<FolderStatsRow> {
    let lib = library(app)?;
    let folder_id = folder_id.to_string();
    lib.read(move |conn| {
        // The command reports zeroes for an unknown id; an agent needs to know
        // it aimed at nothing, so confirm the folder exists first.
        let exists: bool = conn.query_row(
            "SELECT EXISTS (SELECT 1 FROM folders WHERE id = ?1)",
            [folder_id.as_str()],
            |row| row.get(0),
        )?;
        if !exists {
            return Err(AppError::NotFound(format!("folder {folder_id}")));
        }
        Ok(FolderStatsRow::from(
            crate::commands::folders::compute_folder_stats(conn, &folder_id)?,
        ))
    })
    .await
}

pub async fn tags<R: tauri::Runtime>(app: &tauri::AppHandle<R>) -> AppResult<Vec<TagRowWithCount>> {
    let lib = library(app)?;
    lib.read(|conn| {
        Ok(crate::commands::tags::all_tags_in(conn)?
            .into_iter()
            .map(TagRowWithCount::from)
            .collect())
    })
    .await
}

pub async fn smart_folders<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
) -> AppResult<Vec<SmartFolderRow>> {
    let lib = library(app)?;
    lib.read(|conn| {
        Ok(crate::commands::smart_folders::all_smart_folders_in(conn)?
            .into_iter()
            .map(SmartFolderRow::from)
            .collect())
    })
    .await
}

pub async fn stats<R: tauri::Runtime>(app: &tauri::AppHandle<R>) -> AppResult<StatsRow> {
    let lib = library(app)?;
    lib.read(|conn| {
        Ok(StatsRow::from(crate::commands::library::library_stats_in(
            conn,
        )?))
    })
    .await
}

/// A full-library duplicate scan is O(n²) over fingerprints. Cheap enough to
/// offer, expensive enough that an agent in a retry loop shouldn't be able to
/// pin a core. Enforced here rather than in the route so the MCP tool is bound
/// by the same window.
pub const DUPLICATE_SCAN_INTERVAL: std::time::Duration = std::time::Duration::from_secs(30);
static LAST_DUPLICATE_SCAN: std::sync::Mutex<Option<std::time::Instant>> =
    std::sync::Mutex::new(None);

fn claim_duplicate_scan() -> AppResult<()> {
    let mut last = match LAST_DUPLICATE_SCAN.lock() {
        Ok(guard) => guard,
        Err(poisoned) => poisoned.into_inner(),
    };
    let now = std::time::Instant::now();
    if let Some(previous) = *last {
        if now.duration_since(previous) < DUPLICATE_SCAN_INTERVAL {
            return Err(AppError::RateLimited(format!(
                "a duplicate scan runs at most once every {}s",
                DUPLICATE_SCAN_INTERVAL.as_secs()
            )));
        }
    }
    *last = Some(now);
    Ok(())
}

pub async fn duplicates<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
) -> AppResult<DuplicatesResponse> {
    let lib = library(app)?;
    claim_duplicate_scan()?;
    lib.read(|conn| {
        let scan = crate::commands::duplicates::scan_duplicates_in(conn)?;
        let map = |groups: Vec<Vec<crate::commands::assets::AssetSummary>>| {
            groups
                .into_iter()
                .map(|group| group.into_iter().map(AssetRow::from_summary).collect())
                .collect()
        };
        Ok(DuplicatesResponse {
            exact: map(scan.exact),
            visual: map(scan.visual),
        })
    })
    .await
}

/// The cached WebP thumbnail. Preferred over `file_bytes` for "what is this?"
/// questions: already downscaled, always the same format, a few KB.
pub async fn thumb_bytes<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    id: &str,
) -> AppResult<Vec<u8>> {
    if !is_valid_id(id) {
        return Err(AppError::NotFound(format!("asset {id}")));
    }
    let lib = library(app)?;
    let path = lib.thumb_path(id);
    tokio::fs::read(&path)
        .await
        .map_err(|_| AppError::NotFound(format!("no thumbnail for asset {id}")))
}

/// The managed original, with its recorded MIME type. Refuses anything over
/// [`MAX_FILE_BYTES`] instead of streaming it into a model's context.
pub async fn file_bytes<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    id: &str,
) -> AppResult<(Vec<u8>, String)> {
    if !is_valid_id(id) {
        return Err(AppError::NotFound(format!("asset {id}")));
    }
    let lib = library(app)?;
    let lookup = lib.clone();
    let asset_id = id.to_string();
    let (rel_path, mime, size) = lookup
        .read(move |conn| {
            conn.query_row(
                "SELECT rel_path, mime, size FROM assets WHERE id = ?1",
                [asset_id.as_str()],
                |row| {
                    Ok((
                        row.get::<_, String>(0)?,
                        row.get::<_, Option<String>>(1)?,
                        row.get::<_, i64>(2)?,
                    ))
                },
            )
            .map_err(|err| match err {
                rusqlite::Error::QueryReturnedNoRows => {
                    AppError::NotFound(format!("asset {asset_id}"))
                }
                other => other.into(),
            })
        })
        .await?;
    if size as u64 > MAX_FILE_BYTES {
        return Err(AppError::Conflict(format!(
            "asset is {size} bytes, over the {MAX_FILE_BYTES}-byte limit — \
             fetch its thumbnail instead"
        )));
    }
    let bytes = tokio::fs::read(lib.resolve_rel(&rel_path))
        .await
        .map_err(|_| AppError::NotFound(format!("file missing for asset {id}")))?;
    Ok((
        bytes,
        mime.unwrap_or_else(|| "application/octet-stream".into()),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn only_generated_ids_are_accepted() {
        assert!(is_valid_id("asset000000000000001"));
        assert!(!is_valid_id("short"));
        assert!(!is_valid_id("../../../etc/passwd"));
        assert!(
            !is_valid_id("ASSET000000000000001"),
            "uppercase is not ours"
        );
        assert!(!is_valid_id("asset-0000000000001"), "no punctuation");
        assert!(!is_valid_id(&"a".repeat(33)));
    }
}
